// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Y4Zm-cGfdk1GPBS-0KrxtSbtl9gUbnY',
    appId: '1:534527622387:web:98890071d05599f09c4b86',
    messagingSenderId: '534527622387',
    projectId: 'yalla-now-ad0c8',
    authDomain: 'yalla-now-ad0c8.firebaseapp.com',
    databaseURL: 'https://yalla-now-ad0c8-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-now-ad0c8.appspot.com',
    measurementId: 'G-9JNLY936W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9In_J53jqt9H99zvmTDs3HD0RqjoLSA',
    appId: '1:534527622387:android:72e8b4f2a44608839c4b86',
    messagingSenderId: '534527622387',
    projectId: 'yalla-now-ad0c8',
    databaseURL: 'https://yalla-now-ad0c8-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-now-ad0c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKMRUQCmKf8jlqMBoIuQSQvKFcDw3xybI',
    appId: '1:534527622387:ios:bda787e1c89208e69c4b86',
    messagingSenderId: '534527622387',
    projectId: 'yalla-now-ad0c8',
    databaseURL: 'https://yalla-now-ad0c8-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-now-ad0c8.appspot.com',
    androidClientId: '534527622387-22n2ql1plqbganl857acsghaalvcnohd.apps.googleusercontent.com',
    iosClientId: '534527622387-3ik6ll42fddjolvth8251pokehviv390.apps.googleusercontent.com',
    iosBundleId: 'com.yallanowofficial.yallanow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKMRUQCmKf8jlqMBoIuQSQvKFcDw3xybI',
    appId: '1:534527622387:ios:4493257b6890a64c9c4b86',
    messagingSenderId: '534527622387',
    projectId: 'yalla-now-ad0c8',
    databaseURL: 'https://yalla-now-ad0c8-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-now-ad0c8.appspot.com',
    androidClientId: '534527622387-22n2ql1plqbganl857acsghaalvcnohd.apps.googleusercontent.com',
    iosClientId: '534527622387-rmp5n3slk1hptvoj7pb485m3pq4i21jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.yallanow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Y4Zm-cGfdk1GPBS-0KrxtSbtl9gUbnY',
    appId: '1:534527622387:web:5a84881c4236781b9c4b86',
    messagingSenderId: '534527622387',
    projectId: 'yalla-now-ad0c8',
    authDomain: 'yalla-now-ad0c8.firebaseapp.com',
    databaseURL: 'https://yalla-now-ad0c8-default-rtdb.firebaseio.com',
    storageBucket: 'yalla-now-ad0c8.appspot.com',
    measurementId: 'G-GCD926TKX7',
  );

}