// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpTZVqtmF4OXXI0wXrCqlfuvqpiZGjUJU',
    appId: '1:595105457821:web:6b4680e11ae61748155674',
    messagingSenderId: '595105457821',
    projectId: 'yallanowtest',
    authDomain: 'yallanowtest.firebaseapp.com',
    storageBucket: 'yallanowtest.appspot.com',
    measurementId: 'G-NXHD477EPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1afFJuNwNH2g_p2vDZ9ojXhjZpMcZOk',
    appId: '1:595105457821:android:609384c01ffeec66155674',
    messagingSenderId: '595105457821',
    projectId: 'yallanowtest',
    storageBucket: 'yallanowtest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7I9Q9O6GBgXYcga3J2nls5JaDu3xsXtY',
    appId: '1:595105457821:ios:f3d45badda498e44155674',
    messagingSenderId: '595105457821',
    projectId: 'yallanowtest',
    storageBucket: 'yallanowtest.appspot.com',
    iosBundleId: 'com.example.yallanow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7I9Q9O6GBgXYcga3J2nls5JaDu3xsXtY',
    appId: '1:595105457821:ios:f3d45badda498e44155674',
    messagingSenderId: '595105457821',
    projectId: 'yallanowtest',
    storageBucket: 'yallanowtest.appspot.com',
    iosBundleId: 'com.example.yallanow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpTZVqtmF4OXXI0wXrCqlfuvqpiZGjUJU',
    appId: '1:595105457821:web:d3f9bff0dff3ab21155674',
    messagingSenderId: '595105457821',
    projectId: 'yallanowtest',
    authDomain: 'yallanowtest.firebaseapp.com',
    storageBucket: 'yallanowtest.appspot.com',
    measurementId: 'G-79Q6N75X6T',
  );
}
