import 'package:flutter/material.dart';

const Color pKcolor = Color(0xffB20404);
const Color scColor = Color(0xff5A5A5A);
const Color grayColor = Color(0xffF5F5F5);
const Color blackdcolor = Color(0xff240301);
const String savedToken = "token";
const String savedRole = "role";
const String partnerId = "partnerId";
const String partnerType = "partnerType";
const int resturantType = 2;
const int marttType = 1;
const int pharmacyType = 0;
const String notifChannelKey = "basic_channel";
const String baseUrl = "";
const String kUserDetails = "UserDetails";
const String kBasket = "Basket";
const String driverGroup = "Drivers";
const String userGroup = "Riders";
const String kTrips = "kTrips";
const String tokenId = "idToken";
const String providerId = "provider";
const String kNotification = "notifications";
const Locale arabicLoc = Locale('ar');
const Locale englishLoc = Locale('en');
